# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hshigemu <hshigemu@student.42tokyo.>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/02 20:48:30 by hshigemu          #+#    #+#              #
#    Updated: 2020/11/15 15:37:19 by hshigemu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := libft.a
CC := gcc
CFLAGS := -Wall -Wextra -Werror
RM := rm -f

SRCS := ft_isalnum.c ft_isprint.c ft_memcmp.c ft_putchar_fd.c ft_split.c ft_strrchr.c ft_tolower.c \
	ft_atoi.c ft_isalpha.c ft_itoa.c ft_memcpy.c ft_putendl_fd.c ft_strchr.c ft_strlcat.c ft_strmapi.c \
	ft_strtrim.c ft_toupper.c ft_bzero.c ft_isascii.c ft_memccpy.c ft_memmove.c ft_putnbr_fd.c \
	ft_strdup.c ft_strlcpy.c ft_strncmp.c ft_substr.c ft_calloc.c ft_isdigit.c ft_memchr.c \
	ft_memset.c ft_putstr_fd.c ft_strjoin.c ft_strlen.c ft_strnstr.c

BONUS := ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c \
	ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS := $(SRCS:%.c=%.o)
BONUSOBJS := $(BONUS:%.c=%.o)

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)

all:	$(NAME)

clean:
	$(RM) $(OBJS) $(BONUSOBJS)

fclean:	clean
	$(RM) $(NAME)

re:	fclean all

bonus:	all $(BONUSOBJS)
	ar rc $(NAME) $(OBJS) $(BONUSOBJS)

.PHONY:	all clean fclean re bonus
